export const IpcMainToRender = {
  updateAvailable: "updateAvailable",
  updateNotAvailable: "updateNotAvailable",
  updateError: "updateError",
  updateDownloadPaused: "updateDownloadPaused",
  updateDownloadFailed: "updateDownloadFailed",
  updateDownloadSuccess: "updateDownloadSuccess",
  uploadDownloadProgress: "uploadDownloadProgress",
  transferChooseModalData: "transferChooseModalData",
  getContactStoreData: "getContactStoreData",
  transferContactStoreData: "transferContactStoreData",
  downloadSuccess: "downloadSuccess",
  downloadFailed: "downloadFailed",
  downloadCancel: "downloadCancel",
  downloadPaused: "downloadPaused",
  downloadProgress: "downloadProgress",
  captureResponse: "captureResponse",
};

export const IpcRenderToMain = {
  checkForUpdate: "checkForUpdate",
  downloadUpdate: "downloadUpdate",
  quitAndUpdate: "quitAndUpdate",
  showMainWindow: "showMainWindow",
  openChildWindow: "openChildWindow",
  clearSession: "clearSession",
  minimizeWindow: "minimizeWindow",
  maxmizeWindow: "maxmizeWindow",
  closeWindow: "closeWindow",
  showMessageBox: "showMessageBox",
  transferChooseModalData: "transferChooseModalData",
  getContactStoreData: "getContactStoreData",
  transferContactStoreData: "transferContactStoreData",
  setKeyStore: "setKeyStore",
  getKeyStore: "getKeyStore",
  getKeyStoreSync: "getKeyStoreSync",
  getScreenSource: "getScreenSource",
  startDownload: "startDownload",
  pauseDownload: "pauseDownload",
  resumeDownload: "resumeDownload",
  cancelDownload: "cancelDownload",
  getLocalFile: "getLocalFile",
  showInputContextMenu: "showInputContextMenu",
  capture: "capture",
  updateUnreadCount: "updateUnreadCount",
  setUserCachePath: "setUserCachePath",
  getDataPath: "getDataPath",
  dragFile: "dragFile",
  appUpdate: "appUpdate",
  showLogsInFinder: "showLogsInFinder",
  prepareUploadLogs: "prepareUploadLogs",
  hotRelaunch: "hotRelaunch",
};
